apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-frontend
  namespace: hr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-frontend
  template:
    metadata:
      labels:
        app: hr-frontend
    spec:
      containers:
        - name: hr-frontend
          image: aleks13361/hr-frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: frontend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: hr-frontend
  namespace: hr-app
spec:
  selector:
    app: hr-frontend
  ports:
    - port: 80
      targetPort: 5000
  type: NodePort
